version: "3.8"

services:
  django:
    build:
      context: ../..
      dockerfile: run/docker/Dockerfile
    volumes:
      - static:/srv/static
      - media:/srv/media
      - db_files:/srv/db
  # Uncomment these lines the first time you run `docker-compose up`:
  #    environment:
  #      - DJANGO_SUPERUSER_USERNAME=admin
  #      - DJANGO_SUPERUSER_EMAIL=some@email.com
  #      - DJANGO_SUPERUSER_PASSWORD=<a strong password>
  nginx:
    image: nginx:1.25.3
    volumes:
      - static:/srv/static
      - media:/srv/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - django

volumes:
  static:
  media:
    name: winget.pro_uploaded_files
  db_files:
    name: winget.pro_db_files
